# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    default_locale: '%locale%'
    enabled_locales: [ 'ar', 'bg', 'bn', 'bs', 'ca', 'cs', 'de', 'en', 'es', 'eu', 'fr', 'hr', 'id', 'it', 'ja', 'lt', 'ne', 'nl', 'pl', 'pt_BR', 'ro', 'ru', 'sl', 'sq', 'sr_Cyrl', 'sr_Latn', 'tr', 'uk', 'vi', 'zh_CN' ]


    # see https://symfony.com/doc/current/deployment/proxies.html
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]

    translator:
        default_path: '%kernel.project_dir%/translations'

    serializer:
        enable_attributes: true

    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session: true

    esi: true
    fragments: true

when@test:
    framework:
        test: true
        profiler:
            collect: false
        session:
            storage_factory_id: session.storage.factory.mock_file
