# Settings parameters that will be used in the 'services' section
services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    # Event listeners
    App\CoreBundle\EventListener\AssetListener:
        tags:
            - {name: kernel.event_listener, event: vich_uploader.post_remove}

    App\CoreBundle\EventListener\CidReqListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 6}
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    # Sets the user access in a course listener
    App\CoreBundle\EventListener\CourseAccessListener:
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


  # Sets the user access in a course session listener
    App\CoreBundle\EventListener\SessionAccessListener:
        tags:
            - {name: kernel.event_listener, event: chamilo_course.course.session}

    # Setting user
    App\CoreBundle\EventListener\LegacyListener:
        bind:
            $container: '@service_container'
        tags:
            - {name: kernel.event_listener, event: kernel.request, priority: 7}

    # User locale listener
#    App\CoreBundle\EventListener\UserLocaleListener:
#        tags:
#            - {name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin, priority: 15}

    # Settings listener
    App\CoreBundle\EventListener\SettingListener:
        tags:
            - {name: kernel.event_listener, event: sylius.settings.pre_save}

    App\CoreBundle\EventListener\TwigListener:
        tags:
            - {name: kernel.event_listener}

    # Auth listeners
    App\CoreBundle\EventListener\LoginSuccessHandler:
        tags:
            - {name: kernel.event_listener, event: security.interactive_login}

    App\CoreBundle\EventListener\LogoutListener:
        tags:
            - name: kernel.event_listener
              event: Symfony\Component\Security\Http\Event\LogoutEvent
              priority: 20

    App\CoreBundle\EventListener\HTTPExceptionListener:
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

    App\CoreBundle\EventListener\ExceptionListener:
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

    # Entity listeners
    App\CoreBundle\Entity\Listener\ResourceListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    App\CoreBundle\Entity\Listener\ResourceNodeListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    App\CoreBundle\Entity\Listener\SessionListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    # When the Course entity is created/updated
    App\CoreBundle\Entity\Listener\CourseListener:
        arguments: ['@App\CoreBundle\Tool\ToolChain', '@App\CoreBundle\Settings\SettingsManager']
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    # When the User entity is created/updated        -
    App\CoreBundle\Entity\Listener\UserListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    App\CoreBundle\Entity\Listener\UserRelUserListener:
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    App\CoreBundle\Entity\Listener\SkillRelUserListener:
        arguments:
            - '@App\CoreBundle\Settings\SettingsManager'
            - '@router'
            - '@translator'
        tags:
            - {name: doctrine.orm.entity_listener, entity_manager: default, lazy: true}

    App\CoreBundle\EventListener\MessageStatusListener: ~
