homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'

