platform-controllers:
    resource:
        path: '../src/Platform/Transport/Controller/'
        namespace: App\Platform\Transport\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
admin-controllers:
    resource:
        path: '../src/Admin/Transport/Controller/'
        namespace: App\Admin\Transport\Controller
    type: attribute
    prefix: /{_locale}/admin
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
user-controllers:
    resource:
        path: '../src/User/Transport/Controller/'
        namespace: App\User\Transport\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
blog-controllers:
    resource:
        path: '../src/Blog/Transport/Controller/'
        namespace: App\Blog\Transport\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'
calendar-controllers:
    resource:
        path: '../src/Calendar/Transport/Controller/'
        namespace: App\Calendar\Transport\Controller
    type: attribute
    prefix: /{_locale}/calendar
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
event-controllers:
    resource:
        path: '../src/Event/Transport/Controller/'
        namespace: App\Event\Transport\Controller
    type: attribute
    prefix: /{_locale}/event
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'
property-controllers:
    resource:
        path: '../src/Property/Transport/Controller/'
        namespace: App\Property\Transport\Controller
    type: attribute
    prefix: /{_locale}/property
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%app_locales%'

authentication_token:
    path: /api/authentication_token
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/v1/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh


legacy_main:
    path: /main/{name}
    defaults: {_controller: 'App\CoreBundle\Controller\IndexController::classic'}
    requirements:
        name: .+

legacy_plugin:
    path: /plugin/{name}
    defaults: {_controller: 'ChamiloCoreBundle:Legacy:plugin'}
    requirements:
        name: .+

resources_vue:
    path: /resources/{wildcard}
    controller: App\CoreBundle\Controller\IndexController::index
    requirements:
        wildcard: .*
web_ajax:
    path: main/inc/ajax/

web_main:
    path: main/

logout:
    path: /logout
controllers:
    resource:
        path: ../src/CoreBundle/Controller/
        namespace: App\CoreBundle\Controller
    type: attribute

lti_controllers:
    resource:
        path: ../src/LtiBundle/Controller/
        namespace: App\LtiBundle\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

api.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
