homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%locale%'

user-controllers:
    resource:
        path: '../src/User/Transport/Controller/'
        namespace: App\User\Transport\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'

blog-controllers:
    resource:
        path: '../src/Blog/Transport/Controller/'
        namespace: App\Blog\Transport\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%locale%'

